name = "pillpals-push"
main = "src/index.js"
compatibility_date = "2024-09-01"

# VAPID ключи — сгенерированы заново
# ВАЖНО: не коммить в публичный репозиторий!
[vars]
VAPID_PUBLIC_KEY = "BPvoMNF26fkQGP74PDFc1EzqCdd64ofRuJf592ByR6nJIzgLcC-ZLvZ_sP5MSzSZIMrTM6MSH36OOHamq_oYBU8"
VAPID_PRIVATE_JWK = '{"kty":"EC","x":"--gw0Xbp-RAY_vg8MVzUTOoJ13rih9G4l_n3YHJHqck","y":"IzgLcC-ZLvZ_sP5MSzSZIMrTM6MSH36OOHamq_oYBU8","crv":"P-256","d":"sqPEPbu7nIl2DQfSvDx17xZ7VsCzOsEFSJaVPohZPBM"}'
VAPID_SUBJECT = "mailto:xatabeach42@gmail.com"

# KV-хранилище для подписок и расписаний
[[kv_namespaces]]
binding = "PILLS"
id = "56122daf6cf7431db834cf7e17ec566b"

# Cron: проверяем напоминания каждые 2 минуты
[triggers]
crons = ["*/2 * * * *"]
