name = "pillpals-push"
main = "src/index.js"
compatibility_date = "2024-09-01"

# VAPID ключи — сгенерированы заново
# ВАЖНО: не коммить в публичный репозиторий!
[vars]
VAPID_PUBLIC_KEY = "BAuf6NlrKLlW2OAEYeXWrl-7xamHX5mIZqdwUfXiRQpzZjZo8Il9m-tR8cU1gFUN2oHc_JxkXklMUrKkLfDdQdQ"
VAPID_PRIVATE_JWK = '{"kty":"EC","x":"C5_o2WsouVbY4ARh5dauX7vFqYdfmYhmp3BR9eJFCnM","y":"ZjZo8Il9m-tR8cU1gFUN2oHc_JxkXklMUrKkLfDdQdQ","crv":"P-256","d":"Xaw2pFZR5c0KNJhlR917I-6C0ymi6t4uE7QzzDqcFCs"}'
VAPID_SUBJECT = "mailto:xatabeach42@gmail.com"

# KV-хранилище для подписок и расписаний
[[kv_namespaces]]
binding = "PILLS"
id = "56122daf6cf7431db834cf7e17ec566b"

# Cron: проверяем напоминания каждые 2 минуты
[triggers]
crons = ["*/2 * * * *"]
